name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-test:
    name: Lint, type-check, test, and build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          python-version: "3.12"

      - name: Cache uv and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Type check
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest

      - name: Build distribution artifacts
        run: uv build

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist
          if-no-files-found: error

      - name: Publish coverage comment
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_PATH: .
